# Javascript Node CircleCI 2.0 configuration file
#
# https://circleci.com/docs/2.0/language-javascript/
# https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/
#
version: 2

defaults: &defaults
  working_directory: ~/pyout-frontend
  docker:
    - image: circleci/node:10.15.3

jobs:
  install:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - persist_to_workspace:
          root: ~/pyout-frontend
          paths: .

      - run: npm install
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/pyout-frontend

      - run: npm run build
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/pyout-frontend

      - run: npm test
  cache:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/pyout-frontend

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/pyout-frontend
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/pyout-frontend/.npmrc
      - run: npm publish

workflows:
  version: 2
  pr:
    jobs:
      - install:
          filters:
            tags:
              ignore: /.*/
      - build:
          requires:
            - install
      - test:
          requires:
            - install
      - cache:
          requires:
            - build
            - test
